API_BASE_URL = "https://api.example.com"  # ← set your real API URL here
API_TIMEOUT  = 30

GRADUATING_HOURS_THRESHOLD = 21

SERVER = "localhost"
DATABASE = "master"
DRIVER = "ODBC Driver 17 for SQL Server"

USE_TRUSTED_CONNECTION = True

DEFAULT_ROOM_CAPACITY_FALLBACK = 40
DEFAULT_MAX_SECTIONS_PER_COURSE = 3

LOAD_RULES = {
    "Professor": 9,
    "Associate Professor": 12,
    "Assistant Professor": 12,
    "Master": 15,
    "Doctor": 15,
}

ADMIN_LOAD_REDUCTION = 3

ALLOWED_START = "08:00:00"
ALLOWED_END = "16:00:00"

DEFAULT_ROOM_TYPE = "Lecture"

CLEAR_OLD_SCHEDULE = True

MIN_STUDENTS_TO_OPEN_COURSE = 5
MIN_GRADUATING_TO_FORCE_OPEN = 1


GRADUATING_PRIORITY_ENABLED = True